# The name of this instance of ahagon.
name = "ahagon"

[github]

# A GitHub personal access token.
# Be sure to add `repo` privileges.
access_token = ""

# A GitHub OAuth application for this instance of ahagon:
app_client_id = ""
app_client_secret = ""

[web]

# The host ip or domain for the server.
host = "138.197.155.224"

# The port ahagon listens on.
port = 54856

[db]

# The database ahagon uses.
# SQLite file:
file = "main.db"

[[repos]]

# github.com/<owner>/<name>
owner = ""
name = ""

# Who has r+ rights?
reviewers = ["mikopits", "pshuu"]

# Who has 'try' rights?
try_users = []

# Arbitrary secret (e.g. openssl rand -hex 20)
secret = ""

# Found under <https://travis-ci.org/profile/info>.
token = ""
